In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('modified.csv')

In [4]:
dataset.head()

WindGustSpeed  WindSpeed9am  WindSpeed3pm  hours
0             30             6            20      5
1             39             4            17      5
2             85             6             6      1
3             54            30            24      3
4             50            20            28      3

In [5]:
X = dataset.iloc[:, 0:3].values
y = dataset.iloc[:,3].values

In [6]:
X

array([[30,  6, 20],
       [39,  4, 17],
       [85,  6,  6],
       ...,
       [43, 11,  9],
       [46,  6, 28],
       [78, 31, 35]], dtype=int64)

In [7]:
y

array([5, 5, 1, 3, 3, 4, 4, 4, 4, 5, 5, 4, 3, 4, 4, 4, 3, 4, 5, 4, 5, 4,
       6, 6, 4, 4, 3, 2, 3, 3, 4, 4, 5, 5, 4, 3, 5, 4, 4, 3, 5, 4, 5, 5,
       4, 5, 4, 5, 6, 5, 4, 0, 5, 4, 4, 4, 1, 6, 5, 5, 5, 5, 4, 3, 4, 5,
       5, 5, 4, 5, 5, 3, 3, 3, 3, 5, 3, 4, 5, 5, 4, 3, 5, 6, 5, 4, 6, 5,
       5, 1, 3, 3, 4, 4, 4, 4, 5, 5, 4, 3, 4, 4, 4, 3, 4, 5, 4, 5, 4, 6,
       6, 4, 4, 3, 2, 3, 3, 4, 4, 5, 5, 4, 3, 5, 4, 4, 3, 5, 4, 5, 5, 4,
       5, 4, 5, 6, 5, 4, 0, 5, 4, 4, 4, 1, 6, 5, 5, 5, 5, 4, 3, 4, 5, 5,
       5, 4, 5, 5, 3, 3, 3, 3, 5, 3, 4, 5, 5, 4, 3, 5, 6, 5, 4, 6, 5, 5,
       1, 3, 3, 4, 4, 4, 4, 5, 5, 4, 3, 4, 4, 4, 3, 4, 5, 4, 5, 4, 6, 6,
       4, 4, 3, 2, 3, 3, 4, 4, 5, 5, 4, 3, 5, 4, 4, 3, 5, 4, 5, 5, 4, 5,
       4, 5, 6, 5, 4, 0, 5, 4, 4, 4, 1, 6, 5, 5, 5, 5, 4, 3, 4, 5, 5, 5,
       4, 5, 5, 3, 3, 3, 3, 5, 3, 4, 5, 5, 4, 3, 5, 6, 5, 4, 6, 5, 5, 1,
       3, 3, 4, 4, 4, 4, 5, 5, 4, 3, 4, 4, 4, 3, 4, 5, 4, 5, 4, 6, 6, 4,
       4, 3, 2, 3, 3, 4, 4, 5, 5, 4, 3, 5, 4, 4, 3,

In [8]:

import seaborn as sns
%matplotlib inline

sns.set_palette("rainbow")
sns.set_style('darkgrid')

sns.pairplot(dataset)


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
mm=r2_score(y_test, y_pred)  

In [12]:

mm

0.00881032405073845

In [13]:
y_pred

array([4.14213181, 3.98473785, 4.19505707, 4.30673218, 4.2665654 ,
       3.61009049, 3.56401938, 4.1895139 , 4.19583152, 4.25124659,
       4.21476625, 4.29023454, 4.18734905, 4.26227159, 3.87132037,
       4.39870702, 4.15058758, 4.21340254, 4.25006776, 3.90553039,
       4.1924351 , 4.19248783, 4.10559905, 4.22038025, 4.19446781,
       4.32123303, 3.96029427, 4.29587425, 3.84342795, 4.32755064,
       4.05821696, 4.2295047 , 3.96029427, 4.09266459, 4.11411614,
       4.24331876, 4.21686948, 4.03902682, 4.0625727 , 4.27740553,
       4.08348741, 4.02406856, 4.25603341, 4.29951717, 3.72994884,
       4.22174395, 4.34155848, 4.46557848, 4.4750549 , 4.16740226,
       4.31669272, 4.23111492, 4.35555741, 4.19195099, 4.30227129,
       4.0619126 , 4.14576583, 3.91029021, 3.95111709, 3.89663434,
       3.33599668, 4.15176641, 4.15518062, 4.33188828, 4.05689707,
       4.13939549, 3.75849245, 4.15476704, 4.22801774, 4.20398775,
       4.01643106, 4.28248269, 4.21542634, 3.91558717])

In [14]:
dataset['WindGustSpeed'].fillna(value=dataset['WindGustSpeed'].mean(),inplace=True)
dataset['WindSpeed9am'].fillna(value=dataset['WindSpeed9am'].mean(),inplace=True)
dataset['WindSpeed3pm'].fillna(value=dataset['WindSpeed3pm'].mean(),inplace=True)


In [15]:
plt.scatter(X_train ,y_train, color = 'red')


ValueError: x and y must be the same size

In [17]:
import seaborn as sns
sns.set_palette('husl')
tmp = dataset.drop('WindGustSpeed', axis=1)
g = sns.pairplot(tmp, hue='hours', markers='+')
plt.show()

C:\Users\Raghavendra Kulkarni\Anaconda3\lib\site-packages\statsmodels\nonparametric\kde.py:488: RuntimeWarning: invalid value encountered in true_divide
  binned = fast_linbin(X, a, b, gridsize) / (delta * nobs)
C:\Users\Raghavendra Kulkarni\Anaconda3\lib\site-packages\statsmodels\nonparametric\kdetools.py:34: RuntimeWarning: invalid value encountered in double_scalars
  FAC1 = 2*(np.pi*bw/RANGE)**2
